DELIMITER $$
CREATE PROCEDURE ProcDashBoard(in start_date date, in end_date date)
BEGIN

	SELECT
	TRANSACTION
	,COUNT(TRANSACTION)
	,SUM(PROD_UNIT_PRICE * UNIT_AMOUNT) "TOTAL_PRE_PRICE"
	,SUM(UNIT_PRICE * UNIT_AMOUNT) "TOTAL_PRICE"
	,SUM(UNIT_PAY) "TOTAL_PAY"
    ,SUM(UNIT_PRICE * UNIT_AMOUNT) - SUM(UNIT_PAY) "TOTAL_DEPT"
	FROM TRANSACTIONS
	WHERE TIMESTAMP BETWEEN START_DATE 
						AND END_DATE
	GROUP BY TRANSACTION;

END$$
DELIMITER ;
