use qt;
DELIMITER $$
 
CREATE TRIGGER after_products_insert
AFTER INSERT
ON products FOR EACH ROW
BEGIN
	INSERT INTO `qt`.`products_hist`
(
`PROD_ID`,
`PROD_NAME`,
`PROD_DESC`,
`PROD_UNIT`,
`PROD_UNIT_PRICE`,
`PROD_AMOUNT`,
`HIST_USER`,
`HIST_ACTION`,
`HIST_TIMESTAMP`)
VALUES
(
NEW.PROD_ID,
NEW.PROD_NAME,
NEW.PROD_DESC,
NEW.PROD_UNIT,
NEW.PROD_UNIT_PRICE,
NEW.PROD_AMOUNT,
NEW.PROD_LAST_USER_CHANGED,
'insert',
NEW.PROD_LAST_TIME_CHANGED);

END$$
 
DELIMITER ;