/*
-- Query: SELECT * FROM qt.products
LIMIT 0, 1000

-- Date: 2019-11-20 01:38
*/
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (1,'GA NGUYEN CON','GA NGUYEN CON','KG',52000,115);
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (2,'BONG GA','LAM TU GA NGUYEN CON','KG',62000,100);
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (3,'VIT NGUYEN CON','VIT NGUYEN CON','KG',59000,70);
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (4,'GA (1.4 - 1.6)','GA CAT NHO','KG',59000,70);
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (5,'BONG GA (1.4 - 1.6))','BONG GA CAT NHO','KG',62000,25);
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (6,'GA NGUYEN 1.4',NULL,'KG',52000,12);
INSERT INTO `products` (`PROD_ID`,`PROD_NAME`,`PROD_DESC`,`PROD_UNIT`,`PROD_UNIT_PRICE`,`PROD_AMOUNT`) VALUES (7,'BONG GA TA',NULL,'KG',62000,29);
