/*
-- Query: SELECT * FROM qt.roles
LIMIT 0, 1000

-- Date: 2019-11-20 01:39
*/
INSERT INTO `` (`ROLE_ID`,`ROLE_NAME`,`ROLE_DESC`) VALUES (1,'ADMIN','Adminnistrartor');
INSERT INTO `` (`ROLE_ID`,`ROLE_NAME`,`ROLE_DESC`) VALUES (2,'SUPPER_USER','ABOVE USER');
INSERT INTO `` (`ROLE_ID`,`ROLE_NAME`,`ROLE_DESC`) VALUES (3,'USER','USER');
